# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 845e9bf600d0d0db868d5ab83c850ef0c3aa8f2fd7395c5afb353b9409f1e4be5f862de9260fb6fc2d7d7514490bf09bdcbff914d5a7deffa62852a2310675a9

test:
  secret_key_base: 52e8ba41b5517a41cb67a58decb0a75cfc991b3be9d9c64ca01f543851e505dd501e299d048877afba850869ddae62f88938c2b6a1f87b52f7986ca660602d36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
